# NLP Pipeline for np20ng — Nepali News Classification Dataset

This notebook performs a complete NLP pipeline on the **np20ng** (Nepali 20 Newsgroups) dataset, which contains over 200,000 Nepali news documents categorized into 20 news categories.

**Dataset Info:**
- Language: Nepali
- Columns: `category`, `content`, `headline`, `source`
- Size: 200,000+ documents
- Task: Multi-class text classification

## 1. Data Loading

In [1]:
import pandas as pd
import re

In [2]:
# Load the np20ng dataset
df = pd.read_csv('dataset/np20ng.csv')
df

,source,category,heading,content
0,Gorkhapatra,Education,"अटेर गर्दै कतिपय विद्यालय, चैतमै भर्ना अभियान ...","काठमाडौं,चैत्र ७ गते । उपत्याकाका कतिपय विद्या..."
1,Gorkhapatra,Education,"निर्वाचन प्रचारमा विद्यालय, शिक्षक र विद्यार्...","प्रकाश सिलवाल काठमाडौँ, चैत ६ गते । विगतका निर..."
2,Gorkhapatra,Education,विद्यार्थीलाई परम्परागत सीप सिकाउँदै विद्यालय,"अमरराज नहर्की तनहुँ, चैत्र ५ गते । तनहुँको एक ..."
3,Gorkhapatra,Education,आन्दोलन नगर्न शिक्षामन्त्रीको आग्रह,"गोरखापत्र समाचारदाता काठमाडौँ, चैत ३ गते । शिक..."
4,Gorkhapatra,Education,विश्वविद्यालयमा हडताल नगर्न शिक्षामन्त्रीको आग्रह,"काठमाडौं, चैत २ गते। शिक्षा विज्ञान तथा प्रविध..."
...,...,...,...,...
231211,Aarthiknews,Business,अपर नौगाड जलविद्युत् उत्पादनको अन्तिम तयारी,\nदार्चुला । नौगाड गाउँपालिकामा निर्माणाधीन ...
231212,Aarthiknews,Business,कुलेखानी तेस्रो र माथिल्लो त्रिशुली थ्री ए निर...,\nलामो समयसम्म समस्यामा फसेका नेपाल विद्य...
231213,Aarthiknews,Business,माथिल्लो तामाकोशी लागत बढ्नुमा सञ्चय कोषको हात...,"काठमाडौं, पुस १९ । कर्मचारी सञ्चय कोषले साहू म..."
231214,Aarthiknews,Business,नेपाल हाइड्रो डेभलोपरले लाभांश दिने,"काठमाडौं, पुस १० । नेपाल हाइड्रो डेभलोपर लिमिट..."
231215,Aarthiknews,Business,"भारतको शब्द जालमा ऊर्जामन्त्री, विद्युत् व्याप...","काठमाडौं, पुस १० । सरकारले भारत तथा बंगलादेशमा..."

## 2. Data Exploration

In [3]:
df.shape

(231216, 4)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 231216 entries, 0 to 231215
Data columns (total 4 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   source    231216 non-null  object
 1   category  231216 non-null  object
 2   heading   231214 non-null  object
 3   content   231191 non-null  object
dtypes: object(4)
memory usage: 7.1+ MB

In [5]:
df.describe()

,source,category,heading,content
count,231216,231216,231214,231191
unique,10,20,227162,230964
top,Nepalkhabar,Politics,एपीएफ टोलीद्वारा चोरीपैठारीको सामान बरामद,एजेन्सी
freq,69506,31021,58,31

In [6]:
df.isnull().sum()

source       0
category     0
heading      2
content     25
dtype: int64

In [7]:
df['category'].value_counts()

category
Politics         31021
Society          27802
Sports           24392
Economy          23653
Entertainment    22664
World            17431
Business         11645
Bank             10526
Health            9469
Crime             8173
Arts              7712
Technology        6427
Automobile        5152
Market            4373
Literature        4149
Opinion           3945
Lifestyle         3865
Education         3709
Tourism           3177
Employment        1931
Name: count, dtype: int64

In [8]:
df.duplicated().sum()

np.int64(58)

## 3. Data Cleaning

In [9]:
# Drop duplicate rows
df.drop_duplicates(inplace=True)
df.shape

(231158, 4)

In [10]:
# Drop rows where 'content' is null
df.dropna(subset=['content'], inplace=True)
df.shape

(231135, 4)

In [11]:
# Check text length
df['text_length'] = df['content'].apply(len)
df['text_length'].describe()

count    231135.000000
mean       1765.335510
std        1921.260737
min           1.000000
25%         754.000000
50%        1153.000000
75%        2002.000000
max       56398.000000
Name: text_length, dtype: float64

In [12]:
# Filter out very short texts (less than 10 characters)
df = df[df['text_length'] > 10]
df.shape

(231037, 5)

In [13]:
# Clean HTML tags
def clean_html(text):
    return re.sub(r'<.*?>', '', str(text))

df['content'] = df['content'].apply(clean_html)
df.head()

C:\Users\LOQ\AppData\Local\Temp\ipykernel_78944\1858388119.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['content'] = df['content'].apply(clean_html)

,source,category,heading,content,text_length
0,Gorkhapatra,Education,"अटेर गर्दै कतिपय विद्यालय, चैतमै भर्ना अभियान ...","काठमाडौं,चैत्र ७ गते । उपत्याकाका कतिपय विद्या...",2117
1,Gorkhapatra,Education,"निर्वाचन प्रचारमा विद्यालय, शिक्षक र विद्यार्...","प्रकाश सिलवाल काठमाडौँ, चैत ६ गते । विगतका निर...",4536
2,Gorkhapatra,Education,विद्यार्थीलाई परम्परागत सीप सिकाउँदै विद्यालय,"अमरराज नहर्की तनहुँ, चैत्र ५ गते । तनहुँको एक ...",2592
3,Gorkhapatra,Education,आन्दोलन नगर्न शिक्षामन्त्रीको आग्रह,"गोरखापत्र समाचारदाता काठमाडौँ, चैत ३ गते । शिक...",1404
4,Gorkhapatra,Education,विश्वविद्यालयमा हडताल नगर्न शिक्षामन्त्रीको आग्रह,"काठमाडौं, चैत २ गते। शिक्षा विज्ञान तथा प्रविध...",2060

In [14]:
# Remove URLs
def remove_urls(text):
    return re.sub(r'http\S+|www\.\S+', '', str(text))

df['content'] = df['content'].apply(remove_urls)

C:\Users\LOQ\AppData\Local\Temp\ipykernel_78944\2965463412.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['content'] = df['content'].apply(remove_urls)

In [15]:
# Convert to lowercase (for any English/mixed text present)
df['content'] = df['content'].apply(lambda x: str(x).lower())
df.head()

C:\Users\LOQ\AppData\Local\Temp\ipykernel_78944\2318777724.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['content'] = df['content'].apply(lambda x: str(x).lower())

,source,category,heading,content,text_length
0,Gorkhapatra,Education,"अटेर गर्दै कतिपय विद्यालय, चैतमै भर्ना अभियान ...","काठमाडौं,चैत्र ७ गते । उपत्याकाका कतिपय विद्या...",2117
1,Gorkhapatra,Education,"निर्वाचन प्रचारमा विद्यालय, शिक्षक र विद्यार्...","प्रकाश सिलवाल काठमाडौँ, चैत ६ गते । विगतका निर...",4536
2,Gorkhapatra,Education,विद्यार्थीलाई परम्परागत सीप सिकाउँदै विद्यालय,"अमरराज नहर्की तनहुँ, चैत्र ५ गते । तनहुँको एक ...",2592
3,Gorkhapatra,Education,आन्दोलन नगर्न शिक्षामन्त्रीको आग्रह,"गोरखापत्र समाचारदाता काठमाडौँ, चैत ३ गते । शिक...",1404
4,Gorkhapatra,Education,विश्वविद्यालयमा हडताल नगर्न शिक्षामन्त्रीको आग्रह,"काठमाडौं, चैत २ गते। शिक्षा विज्ञान तथा प्रविध...",2060

In [16]:
# Remove special characters but KEEP Nepali Devanagari characters (Unicode range \u0900-\u097F)
def remove_special_chars(text):
    return re.sub(r'[^\u0900-\u097F\s0-9a-zA-Z]', '', str(text))

df['content'] = df['content'].apply(remove_special_chars)
df.head()

C:\Users\LOQ\AppData\Local\Temp\ipykernel_78944\1473178693.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['content'] = df['content'].apply(remove_special_chars)

,source,category,heading,content,text_length
0,Gorkhapatra,Education,"अटेर गर्दै कतिपय विद्यालय, चैतमै भर्ना अभियान ...",काठमाडौंचैत्र ७ गते । उपत्याकाका कतिपय विद्याल...,2117
1,Gorkhapatra,Education,"निर्वाचन प्रचारमा विद्यालय, शिक्षक र विद्यार्...",प्रकाश सिलवाल काठमाडौँ चैत ६ गते । विगतका निर्...,4536
2,Gorkhapatra,Education,विद्यार्थीलाई परम्परागत सीप सिकाउँदै विद्यालय,अमरराज नहर्की तनहुँ चैत्र ५ गते । तनहुँको एक स...,2592
3,Gorkhapatra,Education,आन्दोलन नगर्न शिक्षामन्त्रीको आग्रह,गोरखापत्र समाचारदाता काठमाडौँ चैत ३ गते । शिक्...,1404
4,Gorkhapatra,Education,विश्वविद्यालयमा हडताल नगर्न शिक्षामन्त्रीको आग्रह,काठमाडौं चैत २ गते। शिक्षा विज्ञान तथा प्रविधि...,2060

In [17]:
# Remove extra whitespace
def remove_extra_whitespace(text):
    return re.sub(r'\s+', ' ', str(text)).strip()

df['content'] = df['content'].apply(remove_extra_whitespace)
df.head()

C:\Users\LOQ\AppData\Local\Temp\ipykernel_78944\837835750.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['content'] = df['content'].apply(remove_extra_whitespace)

,source,category,heading,content,text_length
0,Gorkhapatra,Education,"अटेर गर्दै कतिपय विद्यालय, चैतमै भर्ना अभियान ...",काठमाडौंचैत्र ७ गते । उपत्याकाका कतिपय विद्याल...,2117
1,Gorkhapatra,Education,"निर्वाचन प्रचारमा विद्यालय, शिक्षक र विद्यार्...",प्रकाश सिलवाल काठमाडौँ चैत ६ गते । विगतका निर्...,4536
2,Gorkhapatra,Education,विद्यार्थीलाई परम्परागत सीप सिकाउँदै विद्यालय,अमरराज नहर्की तनहुँ चैत्र ५ गते । तनहुँको एक स...,2592
3,Gorkhapatra,Education,आन्दोलन नगर्न शिक्षामन्त्रीको आग्रह,गोरखापत्र समाचारदाता काठमाडौँ चैत ३ गते । शिक्...,1404
4,Gorkhapatra,Education,विश्वविद्यालयमा हडताल नगर्न शिक्षामन्त्रीको आग्रह,काठमाडौं चैत २ गते। शिक्षा विज्ञान तथा प्रविधि...,2060

In [18]:
# Updated shape after cleaning
df.shape

(231037, 5)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 231037 entries, 0 to 231215
Data columns (total 5 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   source       231037 non-null  object
 1   category     231037 non-null  object
 2   heading      231035 non-null  object
 3   content      231037 non-null  object
 4   text_length  231037 non-null  int64
dtypes: int64(1), object(4)
memory usage: 10.6+ MB

In [20]:
df.describe()

         text_length
count  231037.000000
mean     1766.081667
std      1921.326480
min        20.000000
25%       755.000000
50%      1153.000000
75%      2003.000000
max     56398.000000

In [21]:
df.isnull().sum()

source         0
category       0
heading        2
content        0
text_length    0
dtype: int64

In [22]:
df['category'].value_counts()

category
Politics         31020
Society          27800
Sports           24392
Economy          23653
Entertainment    22663
World            17431
Business         11645
Bank             10526
Health            9469
Crime             8172
Arts              7712
Technology        6425
Automobile        5152
Market            4373
Literature        4149
Opinion           3945
Lifestyle         3767
Education         3709
Tourism           3103
Employment        1931
Name: count, dtype: int64

## 4. Text Preprocessing

**Note:** Since this dataset is in **Nepali** (Devanagari script), standard English NLP tools from NLTK (Porter Stemmer, WordNet Lemmatizer, POS Tagger, NER) will NOT work correctly. We use:
- **Whitespace-based tokenization** (suitable for Nepali)
- **Custom Nepali stopword list** for stopword removal
- Stemming, Lemmatization, POS Tagging, and NER are **skipped** as they require Nepali-specific language models

In [23]:
# Tokenization using whitespace splitting (suitable for Nepali text)
df['tokens'] = df['content'].apply(lambda x: str(x).split())
df[['content', 'tokens']].head()

C:\Users\LOQ\AppData\Local\Temp\ipykernel_78944\4191831152.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tokens'] = df['content'].apply(lambda x: str(x).split())

,content,tokens
0,काठमाडौंचैत्र ७ गते । उपत्याकाका कतिपय विद्याल...,"[काठमाडौंचैत्र, ७, गते, ।, उपत्याकाका, कतिपय, ..."
1,प्रकाश सिलवाल काठमाडौँ चैत ६ गते । विगतका निर्...,"[प्रकाश, सिलवाल, काठमाडौँ, चैत, ६, गते, ।, विग..."
2,अमरराज नहर्की तनहुँ चैत्र ५ गते । तनहुँको एक स...,"[अमरराज, नहर्की, तनहुँ, चैत्र, ५, गते, ।, तनहु..."
3,गोरखापत्र समाचारदाता काठमाडौँ चैत ३ गते । शिक्...,"[गोरखापत्र, समाचारदाता, काठमाडौँ, चैत, ३, गते,..."
4,काठमाडौं चैत २ गते। शिक्षा विज्ञान तथा प्रविधि...,"[काठमाडौं, चैत, २, गते।, शिक्षा, विज्ञान, तथा,..."

In [24]:
# Nepali Stopword Removal
# Common Nepali stopwords list
nepali_stopwords = {
    'को', 'मा', 'ले', 'र', 'हो', 'छ', 'गर्ने', 'भएको', 'यो', 'त्यो',
    'एक', 'लागि', 'पनि', 'नै', 'बाट', 'सँग', 'हुने', 'गरेको', 'रहेको',
    'भने', 'गर्न', 'थियो', 'छन्', 'हुन्छ', 'तथा', 'वा', 'कि', 'जस्तो',
    'अनि', 'त', 'नि', 'थिए', 'छैन', 'हुन', 'गरी', 'गर्दा', 'गरे',
    'भन्ने', 'यस', 'उनी', 'उनले', 'यसको', 'त्यस', 'जुन', 'सो', 'अर्को',
    'कुनै', 'सबै', 'दुई', 'तीन', 'हुँदा', 'भएर', 'रहेछ', 'गर्दै',
    'आफ्नो', 'उक्त', 'प्रति', 'बारे', 'अन्य', 'अनुसार', 'समेत',
    'यहाँ', 'त्यहाँ', 'कहाँ', 'कसरी', 'किन', 'कहिले', 'अब', 'तर',
    'भने', 'पछि', 'अगाडि', 'माथि', 'तल', 'भित्र', 'बाहिर',
    'सम्म', 'देखि', 'द्वारा', 'बिना', 'सहित', 'विरुद्ध'
}

df['tokens_no_stop'] = df['tokens'].apply(
    lambda tokens: [word for word in tokens if word not in nepali_stopwords]
)
df[['tokens', 'tokens_no_stop']].head()

C:\Users\LOQ\AppData\Local\Temp\ipykernel_78944\1744379670.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tokens_no_stop'] = df['tokens'].apply(

,tokens,tokens_no_stop
0,"[काठमाडौंचैत्र, ७, गते, ।, उपत्याकाका, कतिपय, ...","[काठमाडौंचैत्र, ७, गते, ।, उपत्याकाका, कतिपय, ..."
1,"[प्रकाश, सिलवाल, काठमाडौँ, चैत, ६, गते, ।, विग...","[प्रकाश, सिलवाल, काठमाडौँ, चैत, ६, गते, ।, विग..."
2,"[अमरराज, नहर्की, तनहुँ, चैत्र, ५, गते, ।, तनहु...","[अमरराज, नहर्की, तनहुँ, चैत्र, ५, गते, ।, तनहु..."
3,"[गोरखापत्र, समाचारदाता, काठमाडौँ, चैत, ३, गते,...","[गोरखापत्र, समाचारदाता, काठमाडौँ, चैत, ३, गते,..."
4,"[काठमाडौं, चैत, २, गते।, शिक्षा, विज्ञान, तथा,...","[काठमाडौं, चैत, २, गते।, शिक्षा, विज्ञान, प्रव..."

In [25]:
# NOTE: Stemming is SKIPPED for Nepali text
# Reason: NLTK's PorterStemmer and other stemmers are designed for English.
# There is no reliable, widely-available Nepali stemmer in standard Python libraries.
# For a production system, consider using a Nepali-specific NLP library.
print("Stemming: SKIPPED (No reliable Nepali stemmer available in standard libraries)")
print("In the reference notebook, PorterStemmer was used for English text.")

Stemming: SKIPPED (No reliable Nepali stemmer available in standard libraries)
In the reference notebook, PorterStemmer was used for English text.

In [26]:
# NOTE: Lemmatization is SKIPPED for Nepali text
# Reason: NLTK's WordNetLemmatizer only supports English.
# Nepali lemmatization requires specialized Nepali morphological analyzers.
print("Lemmatization: SKIPPED (WordNet only supports English)")
print("In the reference notebook, WordNetLemmatizer was used for English text.")

Lemmatization: SKIPPED (WordNet only supports English)
In the reference notebook, WordNetLemmatizer was used for English text.

In [27]:
# NOTE: POS Tagging is SKIPPED for Nepali text
# Reason: NLTK's POS tagger is trained on English corpora.
# It cannot correctly tag Nepali (Devanagari) text.
print("POS Tagging: SKIPPED (NLTK POS tagger is English-only)")
print("In the reference notebook, nltk.pos_tag() was used for English text.")

POS Tagging: SKIPPED (NLTK POS tagger is English-only)
In the reference notebook, nltk.pos_tag() was used for English text.

In [28]:
# NOTE: Named Entity Recognition (NER) is SKIPPED for Nepali text
# Reason: NLTK's NER chunker is trained on English data only.
print("NER: SKIPPED (NLTK NER chunker is English-only)")
print("In the reference notebook, nltk.ne_chunk() was used for English text.")

NER: SKIPPED (NLTK NER chunker is English-only)
In the reference notebook, nltk.ne_chunk() was used for English text.

## 5. Feature Extraction

In [29]:
# TF-IDF Vectorization
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=500)
X_tfidf = tfidf.fit_transform(df['content'])
print(X_tfidf.shape)

(231037, 500)

In [30]:
# Bag of Words (CountVectorizer)
from sklearn.feature_extraction.text import CountVectorizer

bow = CountVectorizer(max_features=500)
X_bow = bow.fit_transform(df['content'])
print(X_bow.shape)

(231037, 500)

In [31]:
# Label Encoding for categories
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['category_encoded'] = le.fit_transform(df['category'])
df[['category', 'category_encoded']].head(10)

C:\Users\LOQ\AppData\Local\Temp\ipykernel_78944\1880048647.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['category_encoded'] = le.fit_transform(df['category'])

    category  category_encoded
0  Education                 6
1  Education                 6
2  Education                 6
3  Education                 6
4  Education                 6
5  Education                 6
6  Education                 6
7  Education                 6
8  Education                 6
9  Education                 6

## 6. Model Building

**Note:** The dataset is large (200K+ rows). Model training may take several minutes.
If execution is too slow, uncomment the sampling lines in the train-test split cell below.

In [32]:
# Train-Test Split
from sklearn.model_selection import train_test_split

# Optional: Uncomment the next 2 lines to sample the data if training is too slow
# sample_df = df.sample(n=20000, random_state=42)
# X_tfidf = tfidf.fit_transform(sample_df['content']); df = sample_df

X_train, X_test, y_train, y_test = train_test_split(
    X_tfidf, df['category_encoded'], test_size=0.2, random_state=42
)
print(X_train.shape, X_test.shape)

(184829, 500) (46208, 500)

In [33]:
# Naive Bayes Classifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, accuracy_score

nb = MultinomialNB()
nb.fit(X_train, y_train)
y_pred_nb = nb.predict(X_test)

print("Naive Bayes Accuracy:", accuracy_score(y_test, y_pred_nb))
print(classification_report(y_test, y_pred_nb))

Naive Bayes Accuracy: 0.5828644390581718
              precision    recall  f1-score   support

           0       0.44      0.10      0.17      1537
           1       0.76      0.36      0.49      1009
           2       0.63      0.42      0.51      2120
           3       0.47      0.05      0.09      2363
           4       0.67      0.50      0.57      1663
           5       0.33      0.63      0.43      4780
           6       0.85      0.32      0.47       760
           7       0.87      0.07      0.13       373
           8       0.67      0.85      0.75      4491
           9       0.63      0.31      0.42      1841
          10       0.60      0.61      0.61       765
          11       0.69      0.23      0.35       797
          12       0.56      0.32      0.41       863
          13       0.79      0.23      0.35       794
          14       0.72      0.86      0.78      6313
          15       0.47      0.63      0.54      5583
          16       0.86      0.85      0.86      4822
          17       0.68      0.42      0.52      1298
          18       0.37      0.11      0.17       611
          19       0.56      0.61      0.58      3425

    accuracy                           0.58     46208
   macro avg       0.63      0.43      0.46     46208
weighted avg       0.61      0.58      0.56     46208

In [34]:
# Logistic Regression Classifier
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)
y_pred_lr = lr.predict(X_test)

print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_lr))
print(classification_report(y_test, y_pred_lr))

Logistic Regression Accuracy: 0.6816135734072022
              precision    recall  f1-score   support

           0       0.53      0.39      0.45      1537
           1       0.68      0.67      0.67      1009
           2       0.66      0.71      0.68      2120
           3       0.45      0.29      0.36      2363
           4       0.70      0.71      0.71      1663
           5       0.48      0.51      0.49      4780
           6       0.74      0.69      0.72       760
           7       0.63      0.48      0.55       373
           8       0.78      0.84      0.81      4491
           9       0.63      0.57      0.60      1841
          10       0.71      0.67      0.69       765
          11       0.58      0.54      0.56       797
          12       0.57      0.45      0.50       863
          13       0.74      0.74      0.74       794
          14       0.81      0.85      0.83      6313
          15       0.60      0.62      0.61      5583
          16       0.89      0.93      0.91      4822
          17       0.64      0.61      0.63      1298
          18       0.52      0.44      0.48       611
          19       0.66      0.74      0.70      3425

    accuracy                           0.68     46208
   macro avg       0.65      0.62      0.63     46208
weighted avg       0.67      0.68      0.68     46208

In [ ]:
# SVM Classifier
from sklearn.svm import SVC

svm = SVC(kernel='linear')
svm.fit(X_train, y_train)
y_pred_svm = svm.predict(X_test)

print("SVM Accuracy:", accuracy_score(y_test, y_pred_svm))
print(classification_report(y_test, y_pred_svm))

In [ ]:
# Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)

print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))

## 7. Evaluation

In [ ]:
# Confusion Matrix - Naive Bayes
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred_nb)
plt.figure(figsize=(14, 10))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=le.classes_, yticklabels=le.classes_)
plt.title('Confusion Matrix - Naive Bayes')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

## 8. Visualization

In [ ]:
# Word Cloud
# NOTE: For Nepali text, you may need a Devanagari-compatible font.
# If the word cloud shows boxes/squares, download a Nepali font
# (e.g., NotoSansDevanagari-Regular.ttf from Google Fonts)
# and set the font_path parameter below.
from wordcloud import WordCloud

text = ' '.join(df['content'].astype(str))
wordcloud = WordCloud(width=800, height=400, background_color='white').generate(text)
# To use Nepali font, uncomment below and update the path:
# wordcloud = WordCloud(width=800, height=400, background_color='white',
#                       font_path='NotoSansDevanagari-Regular.ttf').generate(text)

plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.title('Word Cloud')
plt.show()

In [ ]:
# Text Length Distribution
plt.figure(figsize=(10, 5))
df['text_length'].hist(bins=50)
plt.title('Text Length Distribution')
plt.xlabel('Text Length')
plt.ylabel('Frequency')
plt.show()

In [ ]:
# Category Distribution
plt.figure(figsize=(12, 6))
df['category'].value_counts().plot(kind='bar')
plt.title('Category Distribution')
plt.xlabel('Category')
plt.ylabel('Count')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

In [ ]:
# Model Comparison
models = ['Naive Bayes', 'Logistic Regression', 'SVM', 'Random Forest']
accuracies = [
    accuracy_score(y_test, y_pred_nb),
    accuracy_score(y_test, y_pred_lr),
    accuracy_score(y_test, y_pred_svm),
    accuracy_score(y_test, y_pred_rf)
]

plt.figure(figsize=(10, 5))
plt.bar(models, accuracies, color=['blue', 'green', 'red', 'orange'])
plt.title('Model Comparison')
plt.xlabel('Model')
plt.ylabel('Accuracy')
plt.ylim(0, 1)
plt.show()